### PR TITLE
Add deprecation message for StdEnv/2016.4 and StdEnv/2018.3, change the global default to StdEnv/2020

### PR DESCRIPTION
**Pull request by mboisson**
This would address 
https://github.com/ComputeCanada/software-stack/issues/132
partly. It deprecates, but does not hide (yet).

### CODE REVIEW

**Comment by bartoldeman** [comment]
ok with the deprecation message. Not sure about removing `module-version python/3.7.4 default`, will that change the default python in the old stdenv?

**Comment by mboisson** [comment]
Yes, it would. If we want to keep the same defaults the old stack, we should install ModuleRC recipes from EasyBuild instead of relying on the global modulerc.

**Comment by mboisson** [comment]
I suggest moving these defaults to a separate `MODULERCFILE`, which would get appended to the path by the old `StdEnv` modules

**Review by bartoldeman — APPROVED** [review]
For some strange reason,  lmod/modulerc_2016_2018 is missing in this web view, but I can see it in the command line checkout so lgtm

**Comment by mboisson** [comment]
> For some strange reason, lmod/modulerc_2016_2018 is missing in this web view, but I can see it in the command line checkout so lgtm

that's because I actually merged this separate `modulerc_2016_2018` the other day, so I could test these modified modules

**Pull request merged**
