### PR TITLE
Add support for RSNT_LOCAL_LICENSE_PATH

### PR DESCRIPTION
**Pull request by ofisette**
Second try for site-level license configuration, this time using `RSNT_LOCAL_LICENSE_PATH`.

### CODE REVIEW

**Comment by mboisson** [comment]
lgtm

**Comment by mboisson** [comment]
This is now pushed to the dev repository. Can you do a final test ?

**Comment by ofisette** [comment]
Tested. It works in a `proot` session, finding the license in `RSNT_LOCAL_LICENSE_PATH` and configuring it properly. If I do not set `RSNT_LOCAL_LICENSE_PATH`, the existing behaviour seems unaffected: the module fails to load unless I add the license to my home directory.

**Comment by mboisson** [comment]
This has been deployed to production.

**Pull request merged**
